export const DEFAULT_CHARACTER_POOL = [
    { id: 'goblin', background: '哥布林', rarity: 'COMMON', defaultWeaponId: 'short_sabre', baseStats: { maxHp: 50, str: 10, dex: 6, con: 8, speed: 15 }, icon: '👺' },
    { id: 'goblin_boss', background: '哥布林头目', rarity: 'RARE', defaultWeaponId: 'military_sabre', baseStats: { maxHp: 70, str: 10, dex: 8, con: 8, speed: 12 }, icon: '👹' },
    { id: 'wolf', background: '野狼', rarity: 'COMMON', defaultWeaponId: 'iron_spear', baseStats: { maxHp: 70, str: 10, dex: 8, con: 8, speed: 15 }, icon: '🐺' },
    { id: 'skeleton', background: '骷髅兵', rarity: 'RARE', defaultWeaponId: 'guard_spear', baseStats: { maxHp: 60, str: 12, dex: 8, con: 10, speed: 14 }, icon: '💀' },
    { id: 'ghost', background: '幽灵', rarity: 'RARE', defaultWeaponId: 'hunter_bow', baseStats: { maxHp: 60, str: 8, dex: 12, con: 7, speed: 18 }, icon: '👻' },
    { id: 'vampire', background: '吸血鬼', rarity: 'EPIC', defaultWeaponId: 'knight_sword', baseStats: { maxHp: 100, str: 14, dex: 12, con: 9, speed: 18 }, icon: '🧛' },
    { id: 'demon', background: '恶魔', rarity: 'EPIC', defaultWeaponId: 'roya_spear', baseStats: { maxHp: 120, str: 12, dex: 10, con: 10, speed: 14 }, icon: '👿' },
    { id: 'dragon', background: '暗黑龙', rarity: 'ENEMY', defaultWeaponId: 'twilight_bow', baseStats: { maxHp: 200, str: 12, dex: 16, con: 14, speed: 10 }, icon: '🐲' },
    { id: 'demon_king', background: '魔王', rarity: 'ENEMY', defaultWeaponId: 'frost_spear', baseStats: { maxHp: 300, str: 16, dex: 10, con: 20, speed: 16 }, icon: '👑' },
    { id: 'heavy_smasher', background: '重锤武士', rarity: 'COMMON', defaultWeaponId: 'long_sword', baseStats: { maxHp: 70, str: 14, dex: 10, con: 10, speed: 12 }, icon: '🔨' },
    { id: 'balanced_guard', background: '均衡卫士', rarity: 'COMMON', defaultWeaponId: 'iron_spear', baseStats: { maxHp: 84, str: 12, dex: 10, con: 12, speed: 10 }, icon: '🛡️' },
    { id: 'tank_wall', background: '铁壁坦克', rarity: 'COMMON', defaultWeaponId: 'mercenary_sword', baseStats: { maxHp: 98, str: 10, dex: 10, con: 14, speed: 9 }, icon: '🗿' },
    { id: 'enduring_soldier', background: '耐久战士', rarity: 'RARE', defaultWeaponId: 'military_sabre', baseStats: { maxHp: 84, str: 12, dex: 10, con: 12, speed: 11 }, icon: '🏰' },
    { id: 'swift_striker', background: '疾风剑客', rarity: 'COMMON', defaultWeaponId: 'short_sabre', baseStats: { maxHp: 70, str: 10, dex: 14, con: 10, speed: 15 }, icon: '⚡' },
    { id: 'versatile_fighter', background: '全能斗士', rarity: 'RARE', defaultWeaponId: 'hunter_bow', baseStats: { maxHp: 70, str: 12, dex: 12, con: 10, speed: 16 }, icon: '🌟' },
    { id: 'brute_berserker', background: '蛮力狂战士', rarity: 'COMMON', defaultWeaponId: 'guard_spear', baseStats: { maxHp: 70, str: 16, dex: 6, con: 10, speed: 8 }, icon: '💥' },
    { id: 'fragile_glass_cannon', background: '玻璃大炮', rarity: 'RARE', defaultWeaponId: 'mercenary_sword', baseStats: { maxHp: 42, str: 16, dex: 10, con: 6, speed: 13 }, icon: '💎' },
    { id: 'slow_mountain', background: '不动山岳', rarity: 'COMMON', defaultWeaponId: 'long_sword', baseStats: { maxHp: 112, str: 10, dex: 6, con: 16, speed: 7 }, icon: '⛰️' },
    { id: 'soft_tank', background: '温厚堡垒', rarity: 'COMMON', defaultWeaponId: 'iron_spear', baseStats: { maxHp: 112, str: 6, dex: 10, con: 16, speed: 10 }, icon: '🦁' },
    { id: 'nimble_spearman', background: '轻盈枪兵', rarity: 'RARE', defaultWeaponId: 'hunter_bow', baseStats: { maxHp: 42, str: 10, dex: 16, con: 6, speed: 18 }, icon: '🦅' },
    { id: 'quick_trickster', background: '快手骗子', rarity: 'RARE', defaultWeaponId: 'short_sabre', baseStats: { maxHp: 70, str: 6, dex: 16, con: 10, speed: 17 }, icon: '🎴' },
    { id: 'weak_support', background: '柔弱辅助', rarity: 'COMMON', defaultWeaponId: 'short_sabre', baseStats: { maxHp: 70, str: 7, dex: 10, con: 10, speed: 11 }, icon: '✨' },
    { id: 'clumsy_archer', background: '笨拙弓手', rarity: 'COMMON', defaultWeaponId: 'long_bow', baseStats: { maxHp: 70, str: 10, dex: 7, con: 10, speed: 12 }, icon: '🎯' },
    { id: 'frail_mage', background: '虚弱法师', rarity: 'COMMON', defaultWeaponId: 'iron_spear', baseStats: { maxHp: 49, str: 10, dex: 10, con: 7, speed: 11 }, icon: '🔮' }
];
